"""Initial F2F schema."""
from alembic import op
import sqlalchemy as sa

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table('users', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('email', sa.String(320), nullable=False, unique=True), sa.Column('password_hash', sa.String(255), nullable=False), sa.Column('role', sa.String(32), nullable=False, server_default='CUSTOMER'), sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('apartments', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('name', sa.String(160), nullable=False, unique=True), sa.Column('address', sa.Text(), nullable=False), sa.Column('coordinator_name', sa.String(160), nullable=False, server_default=''), sa.Column('coordinator_phone', sa.String(32), nullable=False, server_default=''), sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.create_table('admins', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False, unique=True), sa.Column('display_name', sa.String(160), nullable=False))
    op.create_table('delivery_partners', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False, unique=True), sa.Column('name', sa.String(160), nullable=False), sa.Column('phone', sa.String(32), nullable=False), sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.create_table('customers', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=True, unique=True), sa.Column('name', sa.String(160), nullable=False), sa.Column('email', sa.String(320), nullable=False), sa.Column('phone', sa.String(32), nullable=False), sa.Column('apartment_id', sa.Integer(), sa.ForeignKey('apartments.id')), sa.Column('flat_number', sa.String(32), nullable=False, server_default=''))
    op.create_table('products', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('name', sa.String(160), nullable=False), sa.Column('category', sa.String(120), nullable=False), sa.Column('unit', sa.String(32), nullable=False), sa.Column('selling_price', sa.Numeric(12,2), nullable=False), sa.Column('purchase_price', sa.Numeric(12,2), nullable=False), sa.Column('minimum_quantity', sa.Numeric(10,3), nullable=False, server_default='0.25'), sa.Column('quantity_step', sa.Numeric(10,3), nullable=False, server_default='0.25'), sa.Column('image_url', sa.String(500), nullable=False, server_default=''), sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.create_table('orders', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('order_id', sa.String(40), nullable=False, unique=True), sa.Column('customer_id', sa.Integer(), sa.ForeignKey('customers.id')), sa.Column('apartment_id', sa.Integer(), sa.ForeignKey('apartments.id'), nullable=False), sa.Column('customer_name', sa.String(160), nullable=False), sa.Column('customer_phone', sa.String(32), nullable=False), sa.Column('customer_email', sa.String(320), nullable=False), sa.Column('flat_number', sa.String(32), nullable=False), sa.Column('delivery_instructions', sa.Text(), nullable=False, server_default=''), sa.Column('order_status', sa.String(40), nullable=False, server_default='RECEIVED'), sa.Column('packing_status', sa.String(32), nullable=False, server_default='PENDING'), sa.Column('payment_status', sa.String(40), nullable=False, server_default='PENDING'), sa.Column('delivery_date', sa.Date(), nullable=False), sa.Column('delivery_window_start', sa.Time(), nullable=False), sa.Column('delivery_window_end', sa.Time(), nullable=False), sa.Column('subtotal', sa.Numeric(12,2), nullable=False), sa.Column('delivery_charge', sa.Numeric(12,2), nullable=False, server_default='0'), sa.Column('discount', sa.Numeric(12,2), nullable=False, server_default='0'), sa.Column('total', sa.Numeric(12,2), nullable=False), sa.Column('bulk_flag', sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('order_items', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('order_id', sa.Integer(), sa.ForeignKey('orders.id'), nullable=False), sa.Column('product_id', sa.Integer(), sa.ForeignKey('products.id'), nullable=False), sa.Column('product_name', sa.String(160), nullable=False), sa.Column('unit', sa.String(32), nullable=False), sa.Column('quantity', sa.Numeric(10,3), nullable=False), sa.Column('unit_price', sa.Numeric(12,2), nullable=False), sa.Column('purchase_price_snapshot', sa.Numeric(12,2), nullable=False), sa.Column('line_total', sa.Numeric(12,2), nullable=False))
    op.create_table('procurement', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('delivery_date', sa.Date(), nullable=False), sa.Column('product_id', sa.Integer(), sa.ForeignKey('products.id'), nullable=False), sa.Column('required_quantity', sa.Numeric(12,3), nullable=False), sa.Column('purchased_quantity', sa.Numeric(12,3), nullable=False, server_default='0'), sa.Column('supplier', sa.String(160), nullable=False, server_default=''), sa.Column('purchase_price', sa.Numeric(12,2), nullable=False, server_default='0'), sa.Column('status', sa.String(32), nullable=False, server_default='PENDING'))
    op.create_table('delivery_partners_dummy', sa.Column('id', sa.Integer(), primary_key=True))
    op.drop_table('delivery_partners_dummy')
    op.create_table('deliveries', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('order_id', sa.Integer(), sa.ForeignKey('orders.id'), nullable=False, unique=True), sa.Column('delivery_partner_id', sa.Integer(), sa.ForeignKey('delivery_partners.id')), sa.Column('status', sa.String(40), nullable=False, server_default='ASSIGNED'), sa.Column('assigned_at', sa.DateTime(timezone=True)), sa.Column('delivered_at', sa.DateTime(timezone=True)), sa.Column('notes', sa.Text(), nullable=False, server_default=''))
    op.create_table('payments', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('order_id', sa.Integer(), sa.ForeignKey('orders.id'), nullable=False, unique=True), sa.Column('status', sa.String(40), nullable=False, server_default='PENDING'), sa.Column('expected_amount', sa.Numeric(12,2), nullable=False), sa.Column('collected_amount', sa.Numeric(12,2), nullable=False, server_default='0'), sa.Column('collector_user_id', sa.Integer(), sa.ForeignKey('users.id')), sa.Column('collected_at', sa.DateTime(timezone=True)), sa.Column('override_by_user_id', sa.Integer(), sa.ForeignKey('users.id')), sa.Column('override_reason', sa.Text(), nullable=False, server_default=''))
    op.create_table('expenses', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('expense_date', sa.Date(), nullable=False), sa.Column('category', sa.String(80), nullable=False), sa.Column('description', sa.Text(), nullable=False, server_default=''), sa.Column('amount', sa.Numeric(12,2), nullable=False), sa.Column('payment_method', sa.String(80), nullable=False, server_default='CASH'), sa.Column('reference', sa.String(160), nullable=False, server_default=''), sa.Column('recorded_by', sa.Integer(), sa.ForeignKey('users.id')))
    op.create_table('bulk_inquiries', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('name', sa.String(160), nullable=False), sa.Column('phone', sa.String(32), nullable=False), sa.Column('email', sa.String(320), nullable=False), sa.Column('apartment_location', sa.String(240), nullable=False), sa.Column('required_delivery_date', sa.Date()), sa.Column('products', sa.Text(), nullable=False, server_default=''), sa.Column('estimated_quantity', sa.Text(), nullable=False, server_default=''), sa.Column('message', sa.Text(), nullable=False, server_default=''), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('notifications', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id')), sa.Column('channel', sa.String(32), nullable=False), sa.Column('event', sa.String(80), nullable=False), sa.Column('recipient', sa.String(320), nullable=False), sa.Column('payload', sa.Text(), nullable=False, server_default='{}'), sa.Column('status', sa.String(32), nullable=False, server_default='PENDING'), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('app_settings', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('key', sa.String(120), nullable=False, unique=True), sa.Column('value', sa.Text(), nullable=False, server_default=''), sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('audit_logs', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id')), sa.Column('action', sa.String(120), nullable=False), sa.Column('entity_type', sa.String(80), nullable=False), sa.Column('entity_id', sa.String(80), nullable=False), sa.Column('detail', sa.Text(), nullable=False, server_default=''), sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()))
    for table, cols in {'users':['email','role'], 'customers':['phone'], 'products':['name','category'], 'orders':['order_id','delivery_date','order_status','payment_status','created_at'], 'order_items':['order_id'], 'procurement':['delivery_date'], 'expenses':['expense_date'], 'bulk_inquiries':['created_at'], 'audit_logs':['action','created_at']}.items():
        for col in cols:
            op.create_index(f'ix_{table}_{col}', table, [col])

def downgrade():
    for table in ['audit_logs','app_settings','notifications','bulk_inquiries','expenses','payments','deliveries','procurement','order_items','orders','products','customers','delivery_partners','admins','apartments','users']:
        op.drop_table(table)
