'use client';
import { useEffect,useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { Suspense } from 'react';
import Link from 'next/link';
import { api,money } from '@/lib/api';
import { Order } from '@/lib/types';
import { OrderStatus } from '@/components/order-status';
function ConfirmationInner(){const sp=useSearchParams();const id=sp.get('order_id');const [o,setO]=useState<Order|null>(null);useEffect(()=>{if(id)api<Order>(`/orders/${encodeURIComponent(id)}`).then(setO)},[id]);if(!o)return <main className="page"><div className="container empty"><h1>Loading your order…</h1></div></main>;return <main className="page"><div className="container"><div className="card card-pad" style={{maxWidth:860,margin:'0 auto'}}><div className="eyebrow">Order confirmed</div><h1 className="h2" style={{fontSize:'2.8rem'}}>Freshness is on the way.</h1><div className="grid grid-2"><div><div className="small muted">Order ID</div><b style={{fontSize:'1.15rem'}}>{o.order_id}</b><div className="small muted" style={{marginTop:18}}>Scheduled Delivery</div><b>{new Date(o.delivery_date).toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</b><div className="small muted">5:00 AM – 7:00 AM</div><div className="small muted" style={{marginTop:18}}>Apartment / Flat</div><b>{o.apartment_id} / {o.flat_number}</b><div className="small muted" style={{marginTop:18}}>Payment</div><b>Pay the delivery partner upon delivery</b></div><div className="notice"><div className="small muted">Total</div><div className="kpi">{money(o.total)}</div><p className="small muted">A confirmation email has been queued for {o.customer_email}.</p></div></div><div className="divider"/><h3>Order progress</h3><OrderStatus status={o.order_status}/><div className="divider"/><h3>Items</h3>{o.items.map(i=><div className="row" key={i.product_id}><span>{i.product_name} × {i.quantity} {i.unit}</span><b>{money(i.line_total)}</b></div>)}<div className="inline-actions" style={{marginTop:18}}><Link className="btn btn-primary" href={`/track?order_id=${encodeURIComponent(o.order_id)}`}>Track Order</Link><Link className="btn btn-secondary" href="/shop">Continue Shopping</Link></div></div></div></main>}

export default function Confirmation(){return <Suspense fallback={<main className="page"><div className="container empty">Loading your order…</div></main>}><ConfirmationInner/></Suspense>}
